-- Tailwind CSS Language Server
-- Installed via: npm install -g @tailwindcss/language-server
-- https://github.com/tailwindlabs/tailwindcss-intellisense
return {
  'neovim/nvim-lspconfig',
  opts = function()
    vim.lsp.config('tailwindcss', {
      cmd = { 'tailwindcss-language-server', '--stdio' },
      capabilities = {
        workspace = {
          didChangeWatchedFiles = {
            dynamicRegistration = false,
          },
        },
      },
      filetypes = {
        'aspnetcorerazor',
        'astro',
        'astro-markdown',
        'blade',
        'clojure',
        'django-html',
        'htmldjango',
        'edge',
        'eelixir',
        'elixir',
        'ejs',
        'erb',
        'eruby',
        'gohtml',
        'gohtmltmpl',
        'haml',
        'handlebars',
        'hbs',
        'html',
        'htmlangular',
        'html-eex',
        'heex',
        'jade',
        'leaf',
        'liquid',
        'markdown',
        'mdx',
        'mustache',
        'njk',
        'nunjucks',
        'php',
        'razor',
        'slim',
        'twig',
        'css',
        'less',
        'postcss',
        'sass',
        'scss',
        'stylus',
        'sugarss',
        'javascript',
        'javascriptreact',
        'reason',
        'rescript',
        'typescript',
        'typescriptreact',
        'vue',
        'svelte',
        'templ',
      },
      settings = {
        tailwindCSS = {
          classAttributes = { 'class', 'className', 'class:list', 'classList', 'ngClass' },
          includeLanguages = {
            eelixir = 'html-eex',
            elixir = 'phoenix-heex',
            eruby = 'erb',
            heex = 'phoenix-heex',
            htmlangular = 'html',
            javascript = 'javascript',
            javascriptreact = 'javascript',
            templ = 'html',
            typescript = 'javascript',
            typescriptreact = 'javascript',
          },
          classFunctions = { 'tv' },
          experimental = {
            classRegex = {
              { '(`.*?`)', '(".*?")', "('.*?')" },
            },
          },
          lint = {
            cssConflict = 'warning',
            invalidApply = 'error',
            invalidConfigPath = 'error',
            invalidScreen = 'error',
            invalidTailwindDirective = 'error',
            invalidVariant = 'error',
            recommendedVariantOrder = 'warning',
          },
          validate = true,
        },
      },
    })
    vim.lsp.enable('tailwindcss')
  end,
}
